ALTER TABLE campanias ADD COLUMN IF NOT EXISTS subproducto_id BIGINT REFERENCES subproductos(id);
ALTER TABLE campanias ADD COLUMN IF NOT EXISTS clientes_alcanzados INTEGER NOT NULL DEFAULT 0;
ALTER TABLE campanias ADD COLUMN IF NOT EXISTS monto_ofertado NUMERIC(18,2) NOT NULL DEFAULT 0;
ALTER TABLE campanias ADD COLUMN IF NOT EXISTS ticket_promedio NUMERIC(18,2) NOT NULL DEFAULT 0;
